language: node_js
node_js:
  - "6"
  - "8"
  - "10"
script:
  - npm run compile
  - npm test -- --coverage
  - npm run test:bundles
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
